### PR TITLE
remove ctypes module; depend on the cty crate

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3af68a6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3af68a6 with merge 3af68a6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-hal/builds/237282602?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3af68a66938c48ed3834b255956a9ee582932170 to master...

**Pull request merged**
