### PR TITLE
document how to write low level bindings

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5e75eab has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5e75eab with merge 5e75eab...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-hal/builds/233423105?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5e75eab47b46ae3c0ea8031f36728b240ae7c820 to master...

**Pull request merged**
