### PR TITLE
rewrite bindings

### PR DESCRIPTION
**Pull request by japaric**
it seems easier to manually copy them from the DYNALIB_FN declarations in the
spark/firmware repo rather than running bindgen.

cc @dbrgn thoughts? This involves more manual work. There's a list of bindings
to write in `src/lib.rs` but it seems that all the items in that list can be
called without running into linker errors.

### CODE REVIEW

**Comment by japaric** [comment]
I got the cloud API working so I'm going to merge this.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 593dafd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 593dafd with merge 593dafd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/particle-hal/builds/231989093?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 593dafd9ee161b6ba993e878128f2d70ffc5c79b to master...

**Comment by dbrgn** [comment]
@japaric looks good, but how do we keep it up to date? the bindgen advantage is that you can just re-run the script against the newer firmware repo and everything will be updated.

maybe we could add some kind of comment with the original C signature, and then a script would check whether the C signature changed somehow, and whether there are new functions that weren't available in a previous version? something like this:

```rust
// DYNALIB_FN(13, hal_core, HAL_device_ID, unsigned(uint8_t*, unsigned))
pub fn HAL_device_ID(dest: *mut uint8_t, dest_len: c_uint) -> c_uint;
```

**Comment by japaric** [comment]
Either that or we could actually write a tool that scans the spark/firmware repo for DYNALIB_FN lines and turns them into an `extern "C"` block that contains all the function signatures. We would have to manually do the maps from ctypes to Rust types (e.g. `c_uint` to `u32`). The downside of this is that the DYNALIB_FN stuff doesn't contain the names of the function arguments so the tool would produce something like `pub fn HAL_device_ID(_: *mut uint8_t, _: c_uint) -> c_uint`.

> the bindgen advantage is that you can just re-run the script against the newer firmware repo and everything will be updated.

Ah, but actually bindgen choked when I ran it over headers that include C++ code so I don't think we can continue using it.

**Comment by dbrgn** [comment]
Also, it looks like the return type is not specified in the `DYNALIB_FN` call?

Maybe @zsup or @m-mcgowan have some ideas?

**Comment by japaric** [comment]
@dbrgn It is there. It's written using C syntax: the return type comes *before* the types of the arguments (before the parentheses). For example, `HAL_PWM_Get_Frequency, uint16_t(uint16_t)` means `fn HAL_PWM_Get_Frequency(_: uint16_t) -> uint16_t` in Rust.

**Comment by dbrgn** [comment]
Ah, you're right, I somehow overlooked it in the example above :)

**Pull request merged**
