### PR TITLE
Generate USB and USART modules

### PR DESCRIPTION
**Pull request by dbrgn**
I tested the `usb::USB_USART_Init` and `usb::USB_USART_Send_Data` functions, they work fine.

USART is untested, but looks straightforward.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @dbrgn! @homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 628f7f1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 628f7f1 with merge 6b34706...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/particle-hal/builds/231580489?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6b3470662f0460fa42673df45d1dc766b860f9e0 to master...

**Pull request merged**
