### PR TITLE
add spark_variable binding

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 64a079f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 64a079f with merge 64a079f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/particle-hal/builds/231997691?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 64a079f29afaf77f095ce2208a48e680bfaf1003 to master...

**Pull request merged**
