### PR TITLE
Add micros method

### PR DESCRIPTION
**Pull request by trezm**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @trezm 

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0fadb60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0fadb60 with merge 0fadb60...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-hal/builds/252236349?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0fadb603f61dc20ad2ec449538a0c20140ef5ac9 to master...

**Pull request merged**
