### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2e65227 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2e65227 with merge 2e65227...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dc216fc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dc216fc with merge dc216fc...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 141433b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 141433b with merge 141433b...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aac9902 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aac9902 with merge aac9902...

**Comment by japaric** [comment]
Tests green. Merging.

**Pull request merged**
