### PR TITLE
tweak the existing API for memory safe data sharing between `loop` and cloud

### PR DESCRIPTION
**Pull request by japaric**
functions.

Also, rename this crate to photon-hal because it has not been tested on other
devices.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f1d7489 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f1d7489 with merge f1d7489...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/particle-hal/builds/233050576?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f1d7489db668a6514c8d7c80e1157938b6db6572 to master...

**Pull request merged**
